### ISSUE TITLE
Setup initial server features

### ISSUE THREAD

**Issue by HugoKempfer** [HugoKempfer/convey-server#1]
The server will expose a simple REST API with the following endpoints:
## Spec

- GET `/sessions/{key}`
- POST `/sessions`
- DELETE `/sessions/{key}`

## Todo

- [x] Setup actix server
- [x] Setup Redis connectivity
- [x] Open sessions
- [x] Retrieve sessions
- [x] Delete sessions
- [x] Docker setup
- [x] OpenAPI specification
- [ ] General infos README
